<?php

/**
 * Implementation of hook_menu().
 */
function loireetcharme_menu() {
  $items= array ();
  $items['fb_form_validate'] = array(
    'title' => 'Facebook validation page',
		'description' => 'Facebook validation page',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'loireetcharme_validate_form',
    'access arguments' => array('Valider facebook'),
 
  );
  return $items;
}


function loireetcharme_validate_form(){
  $form_id = $_POST["form_id"];
  if($form_id){}
  $toreturn = "";

  
  $request_url = 'http://local.loiretcharme/contact-acces';
  $request_headers = array('Content-Type' => 'application/x-www-form-urlencoded');
  $request_method = 'POST';
  $request_retry = 3;
  $data = "submitted[vos_coordonnees][contact_nom_prenom]=Nom / Prénom *&submitted[vos_coordonnees][contact_telephone]=Téléphone *&submitted[vos_coordonnees][contact_tel_bureau]=Tél Bureau &submitted[vos_coordonnees][contact_email]=Email *&submitted[vos_coordonnees][contact_fax]=Fax &submitted[contact_message]=Message &submitted[reference]=&submitted[titre_du_bien]=&details[sid]=&details[page_num]=1&details[page_count]=1&details[finished]=0&form_build_id=form-sbChJx-yeWt6ziaIacc66yyjRgkOICCsLGylebku5XI&form_token=3b-ntVNVfHXE1CNR_fnWZpbFOuDP78bbx3pK5fHVkdA&form_id=webform_client_form_19";
  
  // Send the request.
  $result = drupal_http_request($request_url, $request_headers, $request_method, $data, $request_retry);
  
   return $result;
}
