bs_platform_home:
    path:      /{page}
    defaults:  { _controller: BSPlateformBundle:Advert:index, page: 1 }
    requirements:
        page: \d*
    
bs_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: BSPlateformBundle:Advert:view }
    requirements:
        id: \d+

bs_platform_view_slug:
    path:      /{year}/{slug}.{_format}
    defaults:  { _controller: BSPlateformBundle:Advert:viewSlug, _format: html }
    requirements:
        year:   \d{4}
        format: html|xml
    
bs_platform_add:
    path:      /add
    defaults:  { _controller: BSPlateformBundle:Advert:add }

bs_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: BSPlateformBundle:Advert:edit }
    requirements:
        id: \d+

bs_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: BSPlateformBundle:Advert:delete }
    requirements:
        id: \d+